### ISSUE TITLE
Apply to be  Maintainer

### ISSUE THREAD

**Issue by dixi83** [chaosben/phosphor7#9]
hello @chaosben,

I would like to apply to be (one of the) new maintain(ers). I have hardware and even so now and then projects to apply this software. 
Not sure how this works...

I anyone else would like to support me... feel free to apply as well!
BR Martijn

**Comment by chaosben** [comment]
Hi Martijn!

Do you want to fork the repo? After that, i will archive this one an leave a comment, that your one is the new source of trust.
Or is there another better idea?

*Benjamin*

**Comment by dixi83** [comment]
Hi Benjamin,
I alreade have a up-to-date Fork,
The only other option I could think of to create a new "organization" and fork it in that account so People might have a more logical name than dixi83 ;)
Martijn

**Comment by chaosben** [comment]
The "new organization" sounds good. Feel free to start it. 🤓

**Comment by dixi83** [comment]
ok it's done:
https://github.com/PHP-S7/phosphor7
